### ISSUE TITLE
function "alreadyProcesedMessage" is not working  and get  $mail->messageId empty

### ISSUE THREAD

**Issue by yk134** [yiioverflow/yii2-imap#10]
I am using https://github.com/unyii2/yii2-imap extension to fetch incoming mails to my web app.
it's based on yii2-imap , and facing issue with "alreadyProcesedMessage" function call

foreach( $mailIds as $mailId ) {
$mail = $mailbox->getMail( $mailId ) ;
print_r( $mail->id ) ;//<- $mail-id is Empty 
if( alreadyProcesedMessage( $mail->messageId ) ) {
continue ;
}
$mailbox->readMailParts = false; 
$mail = $mailbox->getMailParts( $mail ) ;
print_r( $mail ) ;
$attachments = $mail->getAttachments(); die;
// foreach( $attachments as $attachment ) {
//  echo ' Attachment:' . $attachment->name . PHP_EOL ;
//unlink( $attachment->filePath ) ;
// }
}

**Comment by yiioverflow** [comment]
@yk134  Can you explain what issue you are facing pls ?

**Comment by yiioverflow** [comment]
can checkout the latest code pls ?
