### ISSUE TITLE
Undefined property: stdClass::$in_reply_to because of empty "reply-to"

### ISSUE THREAD

**Issue by Tansky91** [yiioverflow/yii2-imap#11]
After last update we got this error if mail has no "reply-to" field

class MailBox, function getMail:
$mail->inReplyTo = strtolower($head->in_reply_to);

**Comment by yiioverflow** [comment]
checking

**Comment by Tansky91** [comment]
Hello, i'm still waiting for you

**Comment by yiioverflow** [comment]
Sorry, I was outstation. I will fix this issue in next 8 hrs. Thanks for reporting. Sorry for the delay.

**Comment by yiioverflow** [comment]
Fixed!
