### ISSUE TITLE
Shouldn't you sepparate the config?

### ISSUE THREAD

**Issue by philippfrenzel** [yiioverflow/yii2-imap#2]
So maybe people can manage it within the components? ;)

**Comment by yiioverflow** [comment]
Yes, that would be a nice, I will update it.
Thanks for the comment.

**Comment by yiioverflow** [comment]
Hi @philippfrenzel , can you help me to fix this issue ?

I tried but am getting Error : 

ReflectionException
Class \roopz\imap\Imap does not exist

My config was like

```
    'imap' => [
        'class' => 'roopz\imap\components\Imap',
        'imapPath' => 'host',
        'username' => 'user',
        'password' => 'pass',
        'serverEncoding'=>'utf-8' // utf-8 default.
     ],
```

I can correct it when give me some idea. Thanks.

**Comment by yiioverflow** [comment]
Please ignore my message. Fixed the issue.

Looking forward to your feedback.

**Comment by ROOPARAVICHANDRAN** [comment]
hi, 

can you tell how did you solve this issue
