### ISSUE TITLE
Is It should >7.0.31 PHP Version?

### ISSUE THREAD

**Issue by themilo** [yiioverflow/yii2-imap#20]
![image](https://user-images.githubusercontent.com/22591171/52997170-52a4b780-3452-11e9-83de-4ea614b819ea.png)

**Comment by uldisn** [comment]
1. Your issue related to https://github.com/unyii2/yii2-imap 
2. In your composer is required package symfony/browser-kit, what required PHP 7.1.3, but on your server installed 7.0.31

**Comment by yiioverflow** [comment]
@uldisn can you fix this and make a pull request pls ?

**Comment by uldisn** [comment]
> @uldisn can you fix this and make a pull request pls ?

Its @themilo project problem.
